// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtBnh4Cy50xlTa5YzzU9iFfvXW5Miy1XY',
    appId: '1:181127225960:web:817183f16f39e2e01ad1dd',
    messagingSenderId: '181127225960',
    projectId: 'wadvance-57ece',
    authDomain: 'wadvance-57ece.firebaseapp.com',
    storageBucket: 'wadvance-57ece.appspot.com',
    measurementId: 'G-LWXJDFXKWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmln9zK-U9G4Jg1i7S0p9nzha5uTPDQFk',
    appId: '1:181127225960:android:a500f99bb91567f51ad1dd',
    messagingSenderId: '181127225960',
    projectId: 'wadvance-57ece',
    storageBucket: 'wadvance-57ece.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKzk3khcimW6alkw5v2eeTdABvOCLSEtw',
    appId: '1:181127225960:ios:cc437c46d0bf04891ad1dd',
    messagingSenderId: '181127225960',
    projectId: 'wadvance-57ece',
    storageBucket: 'wadvance-57ece.appspot.com',
    androidClientId: '181127225960-mn9q5k21qoaa85sogm3e8i3h0al06uol.apps.googleusercontent.com',
    iosClientId: '181127225960-7ksd3nn01i8mfd0loska68got9ps49ps.apps.googleusercontent.com',
    iosBundleId: 'com.example.wadForTest',
  );
}
